export enum UserFunctions {
    APPLE_PAY = "APPLE_PAY",
    GOOGLE_PAY = "GOOGLE_PAY",
    SAVE_PM_V2 = "SAVE_PM_V2",
    SUBSCRIPTION_AND_PASS = "SUBSCRIPTION_AND_PASS",
    SHOW_SOCIAL_BUTTONS = "SHOW_SOCIAL_BUTTONS",
    RED_ZONE = "RED_ZONE",
    SPOT_PARKING = "SPOT_PARKING",
    EVENT_LOCK_PAUSE = "EVENT_LOCK_PAUSE",
    END_PHOTO = "END_PHOTO",
    POST_POLYGON_MAP = "POST_POLYGON_MAP"
}
