export enum TRIP_STEP_MODAL {
    CHECK_CURRENT_TRIP = "check_current_trip",
    CHECK_UNPAID_TRIP = "check_unpaid_trip",
    CHECK_CURENT_BIKE = "check_current_bike",
    CHECKING_DEPOSIT = "checking_deposit",
    CREATING_TRIP = "creating_trip",
    LOCK_CONNECTING = "lock_connecting",
    LOCK_OPEN = "lock_open",
    LOCK_RETRY_CLOSING = "lock_retry_closing",
    LOCK_CLOSING = "lock_closing",
    TRIP_CLOSING = "trip_closing",
    TRIP_PAYING = "trip_paying",
    TRIP_PAID = "trip_paid",
    TRIP_PAYMENT_ERROR = "trip_payment_error",
    TRIP_FINISH_PAYMENT = "trip_finish_payment",
    TRIP_CANCEL = "trip_cancel",
    DEPOSIT_UNCAPTURED = "deposit_uncaptured",
    TRIP_REVIEW = "trip_review",
    LOCK_TIMEOUT = "lock_timeout",
    UNLOCK_TIMEOUT = "unlock_timeout",
    VERIFY_LOCK_CLOSED = "verify_lock_closed",
}
